name: Feature request
description: Suggest an idea for this project
title: ""
labels: ["Issue::Enhancement"]

body:
  - type: textarea
    id: is-your-feature-related-to-a-problem
    attributes:
      label: Is your feature request related to a problem
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I don't like this design that [...]
    validations:
      required: false

  - type: textarea
    id: the-solution-i-d-like
    attributes:
      label: The solution I'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Ex. I hope that the tab bar background of Windows 7 is an AERO interface like IE.
    validations:
      required: false

  - type: textarea
    id: screenshots-or-video
    attributes:
      label: Screenshots or video
      description: If is helpful to attach screenshots or video similar to the desired features.
      placeholder: Drag or paste images or videos to upload
    validations:
      required: false

  - type: textarea
    id: alternatives-i-ve-considered
    attributes:
      label: Alternatives I've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Ex. I don't like this design that [...]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Anything to write down or refer to is fine
    validations:
      required: false
